// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GradingService.proto

// Protobuf Java Version: 3.25.1
package edu.fra.uas.webapp.grpc;

public final class GradingService {
  private GradingService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GradesRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:edu.fra.uas.webapp.grpc.GradesRequest)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code edu.fra.uas.webapp.grpc.GradesRequest}
   */
  public static final class GradesRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:edu.fra.uas.webapp.grpc.GradesRequest)
      GradesRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GradesRequest.newBuilder() to construct.
    private GradesRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GradesRequest() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GradesRequest();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.fra.uas.webapp.grpc.GradingService.internal_static_edu_fra_uas_webapp_grpc_GradesRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.fra.uas.webapp.grpc.GradingService.internal_static_edu_fra_uas_webapp_grpc_GradesRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.fra.uas.webapp.grpc.GradingService.GradesRequest.class, edu.fra.uas.webapp.grpc.GradingService.GradesRequest.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof edu.fra.uas.webapp.grpc.GradingService.GradesRequest)) {
        return super.equals(obj);
      }
      edu.fra.uas.webapp.grpc.GradingService.GradesRequest other = (edu.fra.uas.webapp.grpc.GradingService.GradesRequest) obj;

      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static edu.fra.uas.webapp.grpc.GradingService.GradesRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.fra.uas.webapp.grpc.GradingService.GradesRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.fra.uas.webapp.grpc.GradingService.GradesRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.fra.uas.webapp.grpc.GradingService.GradesRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.fra.uas.webapp.grpc.GradingService.GradesRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.fra.uas.webapp.grpc.GradingService.GradesRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.fra.uas.webapp.grpc.GradingService.GradesRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.fra.uas.webapp.grpc.GradingService.GradesRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static edu.fra.uas.webapp.grpc.GradingService.GradesRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static edu.fra.uas.webapp.grpc.GradingService.GradesRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.fra.uas.webapp.grpc.GradingService.GradesRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.fra.uas.webapp.grpc.GradingService.GradesRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(edu.fra.uas.webapp.grpc.GradingService.GradesRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code edu.fra.uas.webapp.grpc.GradesRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:edu.fra.uas.webapp.grpc.GradesRequest)
        edu.fra.uas.webapp.grpc.GradingService.GradesRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.fra.uas.webapp.grpc.GradingService.internal_static_edu_fra_uas_webapp_grpc_GradesRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.fra.uas.webapp.grpc.GradingService.internal_static_edu_fra_uas_webapp_grpc_GradesRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu.fra.uas.webapp.grpc.GradingService.GradesRequest.class, edu.fra.uas.webapp.grpc.GradingService.GradesRequest.Builder.class);
      }

      // Construct using edu.fra.uas.webapp.grpc.GradingService.GradesRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.fra.uas.webapp.grpc.GradingService.internal_static_edu_fra_uas_webapp_grpc_GradesRequest_descriptor;
      }

      @java.lang.Override
      public edu.fra.uas.webapp.grpc.GradingService.GradesRequest getDefaultInstanceForType() {
        return edu.fra.uas.webapp.grpc.GradingService.GradesRequest.getDefaultInstance();
      }

      @java.lang.Override
      public edu.fra.uas.webapp.grpc.GradingService.GradesRequest build() {
        edu.fra.uas.webapp.grpc.GradingService.GradesRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public edu.fra.uas.webapp.grpc.GradingService.GradesRequest buildPartial() {
        edu.fra.uas.webapp.grpc.GradingService.GradesRequest result = new edu.fra.uas.webapp.grpc.GradingService.GradesRequest(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.fra.uas.webapp.grpc.GradingService.GradesRequest) {
          return mergeFrom((edu.fra.uas.webapp.grpc.GradingService.GradesRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(edu.fra.uas.webapp.grpc.GradingService.GradesRequest other) {
        if (other == edu.fra.uas.webapp.grpc.GradingService.GradesRequest.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:edu.fra.uas.webapp.grpc.GradesRequest)
    }

    // @@protoc_insertion_point(class_scope:edu.fra.uas.webapp.grpc.GradesRequest)
    private static final edu.fra.uas.webapp.grpc.GradingService.GradesRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new edu.fra.uas.webapp.grpc.GradingService.GradesRequest();
    }

    public static edu.fra.uas.webapp.grpc.GradingService.GradesRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GradesRequest>
        PARSER = new com.google.protobuf.AbstractParser<GradesRequest>() {
      @java.lang.Override
      public GradesRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<GradesRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GradesRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public edu.fra.uas.webapp.grpc.GradingService.GradesRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GradesResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:edu.fra.uas.webapp.grpc.GradesResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .google.protobuf.DoubleValue grades = 1;</code>
     */
    java.util.List<com.google.protobuf.DoubleValue> 
        getGradesList();
    /**
     * <code>repeated .google.protobuf.DoubleValue grades = 1;</code>
     */
    com.google.protobuf.DoubleValue getGrades(int index);
    /**
     * <code>repeated .google.protobuf.DoubleValue grades = 1;</code>
     */
    int getGradesCount();
    /**
     * <code>repeated .google.protobuf.DoubleValue grades = 1;</code>
     */
    java.util.List<? extends com.google.protobuf.DoubleValueOrBuilder> 
        getGradesOrBuilderList();
    /**
     * <code>repeated .google.protobuf.DoubleValue grades = 1;</code>
     */
    com.google.protobuf.DoubleValueOrBuilder getGradesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code edu.fra.uas.webapp.grpc.GradesResponse}
   */
  public static final class GradesResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:edu.fra.uas.webapp.grpc.GradesResponse)
      GradesResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GradesResponse.newBuilder() to construct.
    private GradesResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GradesResponse() {
      grades_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GradesResponse();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.fra.uas.webapp.grpc.GradingService.internal_static_edu_fra_uas_webapp_grpc_GradesResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.fra.uas.webapp.grpc.GradingService.internal_static_edu_fra_uas_webapp_grpc_GradesResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.fra.uas.webapp.grpc.GradingService.GradesResponse.class, edu.fra.uas.webapp.grpc.GradingService.GradesResponse.Builder.class);
    }

    public static final int GRADES_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<com.google.protobuf.DoubleValue> grades_;
    /**
     * <code>repeated .google.protobuf.DoubleValue grades = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.google.protobuf.DoubleValue> getGradesList() {
      return grades_;
    }
    /**
     * <code>repeated .google.protobuf.DoubleValue grades = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.google.protobuf.DoubleValueOrBuilder> 
        getGradesOrBuilderList() {
      return grades_;
    }
    /**
     * <code>repeated .google.protobuf.DoubleValue grades = 1;</code>
     */
    @java.lang.Override
    public int getGradesCount() {
      return grades_.size();
    }
    /**
     * <code>repeated .google.protobuf.DoubleValue grades = 1;</code>
     */
    @java.lang.Override
    public com.google.protobuf.DoubleValue getGrades(int index) {
      return grades_.get(index);
    }
    /**
     * <code>repeated .google.protobuf.DoubleValue grades = 1;</code>
     */
    @java.lang.Override
    public com.google.protobuf.DoubleValueOrBuilder getGradesOrBuilder(
        int index) {
      return grades_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < grades_.size(); i++) {
        output.writeMessage(1, grades_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < grades_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, grades_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof edu.fra.uas.webapp.grpc.GradingService.GradesResponse)) {
        return super.equals(obj);
      }
      edu.fra.uas.webapp.grpc.GradingService.GradesResponse other = (edu.fra.uas.webapp.grpc.GradingService.GradesResponse) obj;

      if (!getGradesList()
          .equals(other.getGradesList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getGradesCount() > 0) {
        hash = (37 * hash) + GRADES_FIELD_NUMBER;
        hash = (53 * hash) + getGradesList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static edu.fra.uas.webapp.grpc.GradingService.GradesResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.fra.uas.webapp.grpc.GradingService.GradesResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.fra.uas.webapp.grpc.GradingService.GradesResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.fra.uas.webapp.grpc.GradingService.GradesResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.fra.uas.webapp.grpc.GradingService.GradesResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.fra.uas.webapp.grpc.GradingService.GradesResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.fra.uas.webapp.grpc.GradingService.GradesResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.fra.uas.webapp.grpc.GradingService.GradesResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static edu.fra.uas.webapp.grpc.GradingService.GradesResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static edu.fra.uas.webapp.grpc.GradingService.GradesResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.fra.uas.webapp.grpc.GradingService.GradesResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.fra.uas.webapp.grpc.GradingService.GradesResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(edu.fra.uas.webapp.grpc.GradingService.GradesResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code edu.fra.uas.webapp.grpc.GradesResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:edu.fra.uas.webapp.grpc.GradesResponse)
        edu.fra.uas.webapp.grpc.GradingService.GradesResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.fra.uas.webapp.grpc.GradingService.internal_static_edu_fra_uas_webapp_grpc_GradesResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.fra.uas.webapp.grpc.GradingService.internal_static_edu_fra_uas_webapp_grpc_GradesResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu.fra.uas.webapp.grpc.GradingService.GradesResponse.class, edu.fra.uas.webapp.grpc.GradingService.GradesResponse.Builder.class);
      }

      // Construct using edu.fra.uas.webapp.grpc.GradingService.GradesResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (gradesBuilder_ == null) {
          grades_ = java.util.Collections.emptyList();
        } else {
          grades_ = null;
          gradesBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.fra.uas.webapp.grpc.GradingService.internal_static_edu_fra_uas_webapp_grpc_GradesResponse_descriptor;
      }

      @java.lang.Override
      public edu.fra.uas.webapp.grpc.GradingService.GradesResponse getDefaultInstanceForType() {
        return edu.fra.uas.webapp.grpc.GradingService.GradesResponse.getDefaultInstance();
      }

      @java.lang.Override
      public edu.fra.uas.webapp.grpc.GradingService.GradesResponse build() {
        edu.fra.uas.webapp.grpc.GradingService.GradesResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public edu.fra.uas.webapp.grpc.GradingService.GradesResponse buildPartial() {
        edu.fra.uas.webapp.grpc.GradingService.GradesResponse result = new edu.fra.uas.webapp.grpc.GradingService.GradesResponse(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(edu.fra.uas.webapp.grpc.GradingService.GradesResponse result) {
        if (gradesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            grades_ = java.util.Collections.unmodifiableList(grades_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.grades_ = grades_;
        } else {
          result.grades_ = gradesBuilder_.build();
        }
      }

      private void buildPartial0(edu.fra.uas.webapp.grpc.GradingService.GradesResponse result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.fra.uas.webapp.grpc.GradingService.GradesResponse) {
          return mergeFrom((edu.fra.uas.webapp.grpc.GradingService.GradesResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(edu.fra.uas.webapp.grpc.GradingService.GradesResponse other) {
        if (other == edu.fra.uas.webapp.grpc.GradingService.GradesResponse.getDefaultInstance()) return this;
        if (gradesBuilder_ == null) {
          if (!other.grades_.isEmpty()) {
            if (grades_.isEmpty()) {
              grades_ = other.grades_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureGradesIsMutable();
              grades_.addAll(other.grades_);
            }
            onChanged();
          }
        } else {
          if (!other.grades_.isEmpty()) {
            if (gradesBuilder_.isEmpty()) {
              gradesBuilder_.dispose();
              gradesBuilder_ = null;
              grades_ = other.grades_;
              bitField0_ = (bitField0_ & ~0x00000001);
              gradesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getGradesFieldBuilder() : null;
            } else {
              gradesBuilder_.addAllMessages(other.grades_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                com.google.protobuf.DoubleValue m =
                    input.readMessage(
                        com.google.protobuf.DoubleValue.parser(),
                        extensionRegistry);
                if (gradesBuilder_ == null) {
                  ensureGradesIsMutable();
                  grades_.add(m);
                } else {
                  gradesBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<com.google.protobuf.DoubleValue> grades_ =
        java.util.Collections.emptyList();
      private void ensureGradesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          grades_ = new java.util.ArrayList<com.google.protobuf.DoubleValue>(grades_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.google.protobuf.DoubleValue, com.google.protobuf.DoubleValue.Builder, com.google.protobuf.DoubleValueOrBuilder> gradesBuilder_;

      /**
       * <code>repeated .google.protobuf.DoubleValue grades = 1;</code>
       */
      public java.util.List<com.google.protobuf.DoubleValue> getGradesList() {
        if (gradesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(grades_);
        } else {
          return gradesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .google.protobuf.DoubleValue grades = 1;</code>
       */
      public int getGradesCount() {
        if (gradesBuilder_ == null) {
          return grades_.size();
        } else {
          return gradesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .google.protobuf.DoubleValue grades = 1;</code>
       */
      public com.google.protobuf.DoubleValue getGrades(int index) {
        if (gradesBuilder_ == null) {
          return grades_.get(index);
        } else {
          return gradesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .google.protobuf.DoubleValue grades = 1;</code>
       */
      public Builder setGrades(
          int index, com.google.protobuf.DoubleValue value) {
        if (gradesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGradesIsMutable();
          grades_.set(index, value);
          onChanged();
        } else {
          gradesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.DoubleValue grades = 1;</code>
       */
      public Builder setGrades(
          int index, com.google.protobuf.DoubleValue.Builder builderForValue) {
        if (gradesBuilder_ == null) {
          ensureGradesIsMutable();
          grades_.set(index, builderForValue.build());
          onChanged();
        } else {
          gradesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.DoubleValue grades = 1;</code>
       */
      public Builder addGrades(com.google.protobuf.DoubleValue value) {
        if (gradesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGradesIsMutable();
          grades_.add(value);
          onChanged();
        } else {
          gradesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.DoubleValue grades = 1;</code>
       */
      public Builder addGrades(
          int index, com.google.protobuf.DoubleValue value) {
        if (gradesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGradesIsMutable();
          grades_.add(index, value);
          onChanged();
        } else {
          gradesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.DoubleValue grades = 1;</code>
       */
      public Builder addGrades(
          com.google.protobuf.DoubleValue.Builder builderForValue) {
        if (gradesBuilder_ == null) {
          ensureGradesIsMutable();
          grades_.add(builderForValue.build());
          onChanged();
        } else {
          gradesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.DoubleValue grades = 1;</code>
       */
      public Builder addGrades(
          int index, com.google.protobuf.DoubleValue.Builder builderForValue) {
        if (gradesBuilder_ == null) {
          ensureGradesIsMutable();
          grades_.add(index, builderForValue.build());
          onChanged();
        } else {
          gradesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.DoubleValue grades = 1;</code>
       */
      public Builder addAllGrades(
          java.lang.Iterable<? extends com.google.protobuf.DoubleValue> values) {
        if (gradesBuilder_ == null) {
          ensureGradesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, grades_);
          onChanged();
        } else {
          gradesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.DoubleValue grades = 1;</code>
       */
      public Builder clearGrades() {
        if (gradesBuilder_ == null) {
          grades_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          gradesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.DoubleValue grades = 1;</code>
       */
      public Builder removeGrades(int index) {
        if (gradesBuilder_ == null) {
          ensureGradesIsMutable();
          grades_.remove(index);
          onChanged();
        } else {
          gradesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.DoubleValue grades = 1;</code>
       */
      public com.google.protobuf.DoubleValue.Builder getGradesBuilder(
          int index) {
        return getGradesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .google.protobuf.DoubleValue grades = 1;</code>
       */
      public com.google.protobuf.DoubleValueOrBuilder getGradesOrBuilder(
          int index) {
        if (gradesBuilder_ == null) {
          return grades_.get(index);  } else {
          return gradesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .google.protobuf.DoubleValue grades = 1;</code>
       */
      public java.util.List<? extends com.google.protobuf.DoubleValueOrBuilder> 
           getGradesOrBuilderList() {
        if (gradesBuilder_ != null) {
          return gradesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(grades_);
        }
      }
      /**
       * <code>repeated .google.protobuf.DoubleValue grades = 1;</code>
       */
      public com.google.protobuf.DoubleValue.Builder addGradesBuilder() {
        return getGradesFieldBuilder().addBuilder(
            com.google.protobuf.DoubleValue.getDefaultInstance());
      }
      /**
       * <code>repeated .google.protobuf.DoubleValue grades = 1;</code>
       */
      public com.google.protobuf.DoubleValue.Builder addGradesBuilder(
          int index) {
        return getGradesFieldBuilder().addBuilder(
            index, com.google.protobuf.DoubleValue.getDefaultInstance());
      }
      /**
       * <code>repeated .google.protobuf.DoubleValue grades = 1;</code>
       */
      public java.util.List<com.google.protobuf.DoubleValue.Builder> 
           getGradesBuilderList() {
        return getGradesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.google.protobuf.DoubleValue, com.google.protobuf.DoubleValue.Builder, com.google.protobuf.DoubleValueOrBuilder> 
          getGradesFieldBuilder() {
        if (gradesBuilder_ == null) {
          gradesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.google.protobuf.DoubleValue, com.google.protobuf.DoubleValue.Builder, com.google.protobuf.DoubleValueOrBuilder>(
                  grades_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          grades_ = null;
        }
        return gradesBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:edu.fra.uas.webapp.grpc.GradesResponse)
    }

    // @@protoc_insertion_point(class_scope:edu.fra.uas.webapp.grpc.GradesResponse)
    private static final edu.fra.uas.webapp.grpc.GradingService.GradesResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new edu.fra.uas.webapp.grpc.GradingService.GradesResponse();
    }

    public static edu.fra.uas.webapp.grpc.GradingService.GradesResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GradesResponse>
        PARSER = new com.google.protobuf.AbstractParser<GradesResponse>() {
      @java.lang.Override
      public GradesResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<GradesResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GradesResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public edu.fra.uas.webapp.grpc.GradingService.GradesResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_edu_fra_uas_webapp_grpc_GradesRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_edu_fra_uas_webapp_grpc_GradesRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_edu_fra_uas_webapp_grpc_GradesResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_edu_fra_uas_webapp_grpc_GradesResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024GradingService.proto\022\027edu.fra.uas.weba" +
      "pp.grpc\032\036google/protobuf/wrappers.proto\"" +
      "\017\n\rGradesRequest\">\n\016GradesResponse\022,\n\006gr" +
      "ades\030\001 \003(\0132\034.google.protobuf.DoubleValue" +
      "2\223\003\n\rGradesService\022]\n\nlistGrades\022&.edu.f" +
      "ra.uas.webapp.grpc.GradesRequest\032\'.edu.f" +
      "ra.uas.webapp.grpc.GradesResponse\022M\n\020fin" +
      "dGradeByIndex\022\033.google.protobuf.Int64Val" +
      "ue\032\034.google.protobuf.DoubleValue\022D\n\010addG" +
      "rade\022\034.google.protobuf.DoubleValue\032\032.goo" +
      "gle.protobuf.BoolValue\022F\n\013updateGrade\022\033." +
      "google.protobuf.Int64Value\032\032.google.prot" +
      "obuf.BoolValue\022F\n\013deleteGrade\022\033.google.p" +
      "rotobuf.Int64Value\032\032.google.protobuf.Boo" +
      "lValueb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.WrappersProto.getDescriptor(),
        });
    internal_static_edu_fra_uas_webapp_grpc_GradesRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_edu_fra_uas_webapp_grpc_GradesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_edu_fra_uas_webapp_grpc_GradesRequest_descriptor,
        new java.lang.String[] { });
    internal_static_edu_fra_uas_webapp_grpc_GradesResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_edu_fra_uas_webapp_grpc_GradesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_edu_fra_uas_webapp_grpc_GradesResponse_descriptor,
        new java.lang.String[] { "Grades", });
    com.google.protobuf.WrappersProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
