spring.application.name=webapp
logging.level.edu.fra.uas=DEBUG
# ----------------------------------------
# GraphQL Configuration
# ----------------------------------------
# Enable GraphQL Playground
spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql
# ----------------------------------------
# Database (Supabase / PostgreSQL)
# ----------------------------------------
spring.datasource.url=jdbc:postgresql://145.223.118.106:5433/postgres?sslmode=disable
spring.datasource.username=postgres
spring.datasource.password=I0fKkntdFxsdT49JAZTVKAEUErJRTv3sP29xsgkEGrMC2C2pz0feqUOLLbFN8ndP

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
