spring.application.name=webapp
logging.level.edu.fra.uas=DEBUG
# ----------------------------------------
# GraphQL Configuration
# ----------------------------------------
# Enable GraphQL Playground
spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql